# Dependabot will also update hardcoded image: fields in templates/*.yaml
# but putting them in values.yaml is useful for updating containers within a
# subchart if they don't release a new chart version for every container update
image:
  repository: traefik/whoami
  tag: v1.11@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
