apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
spec:
  rules:
    # argocd.{{ .Values.domain }} is handled directly by cloudflared
    - host: argocd.local.{{ .Values.domain }}
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  number: 80
            path: /
            pathType: Prefix