apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: traefik
spec:
  secretName: wildcard-local-tls
  dnsNames:
    - "local.{{ .Values.domain }}"
    - "*.local.{{ .Values.domain }}"
  issuerRef:
    name: cloudflare-issuer
    kind: Issuer
