# https://docs.cilium.io/en/stable/network/l2-announcements/
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: talos
spec:
  externalIPs: false
  loadBalancerIPs: true
