apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami
spec:
  # .Release.Name will be the name of the directory (e.g. whoami)
  # so will resolve to e.g. host: whoami.mydomain.com
  # Can hardcode, but this example allows the chart to
  # be duplicated and the host won't clash with the original
  hostnames:
    - {{ .Release.Name }}.{{ .Values.domain }}
    - {{ .Release.Name }}.local.{{ .Values.domain }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ''
          kind: Service
          name: whoami
          port: 80
          weight: 1
